<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Color/Xerox-Color-800/1000-Presses/" LinkText="cliquez ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Color/Xerox-Color-8250-Production-Printer/" LinkText="cliquez ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" LinkText="Livre blanc produit AltaLink" Destination="/Products-and-Services/Office/Products/BW-Multifunction/AltaLink-B8045/B8055/B8065/B8075/B8090/"/>
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Mono/Xerox-Nuvera-100/288-EA-Digital-Production-System/" LinkText="Global_Configurator" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Mono/Xerox-Nuvera-100/120/144-EA-Digital-Production-System/" LinkText="ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Mono/Xerox-Nuvera-200/288-EA-Digital-Production-System/" LinkText="ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Mono/DocuTech-HighLight-Color-Systems/" LinkText="ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Our-Value-to-Customers/Our-Value-to-Customers/" LinkText="Proposition de valeur Production" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Tools/SmartPad/" LinkText="ici" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="Signals" TargetUrl="https://www.xeroxresponse2.com/portal/Account/SignIn" Destination="Global_Configurator" LinkText="Online Configurator" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="Lamp" TargetUrl="https://www.office.xerox.com/resellers/" LinkText="Get Pricing" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" LinkText="Global_Configurator" Destination="/Products-and-Services/Production/Products/Production-Mono/Xerox-Nuvera-200/288-EA-Digital-Production-System/" />
<!-- <ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="regular Comment" LinkText="Global_Configurator" /> -->
<%-- <ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="server comment" LinkText="Global_Configurator" /> --%>
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Products-and-Services/Production/Products/Production-Mono/Xerox-Nuvera-300/288-EA-Digital-Production-System/" LinkText="Global_Configurator" />