<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825692" LinkText="guide du programme de l'&eacute;v&eacute;nement" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="Signals" TargetUrl="https://www.xeroxresponse2.com/portal/Account/SignIn" Destination="Event_Site_Builder" LinkText="Event Site Builder" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/Tools/Events-Technology-and-Registration-Systems/" LinkText="guide de l'utilisateur par &eacute;tapes" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825567" LinkText="Document relatif aux r&ocirc;les et aux responsabilit&eacute;s <span class='pdf_text'>(Mod&egrave;le Excel.)</span>" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825384" LinkText="Mod&egrave;le de budget <span class='pdf_text'>(Mod&egrave;le Excel.)</span>" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825623" LinkText="E-mail <span class='pdf_text'>Outlook (.OFT) modifiables.</span>" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="Signals" TargetUrl="https://www.xeroxresponse2.com/portal/Account/SignIn" Destination="Event_Site_Builder" LinkText="<img src='../../../images/products/connectKey-Resources-EventSiteBuilder.jpg'/><br><b>Event Site Builder</b> &ndash; Simplifie de nombreuses t&acirc;ches de promotion et d'organisation d'&eacute;v&eacute;nements"/>
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825580" LinkText="Affichage pour mur arri&egrave;re 20&rsquo; x 8&rsquo; (6,096 m x 2,438 m)" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825573" LinkText="Stand parapluie 10&rsquo; x 8&rsquo; (3,048 m x 2,438 m)" />
<ResellerViewControls:BackpackLink runat="server" TargetSystem="SmartCentre" TargetUrl="https://smartcentre.xerox.com/auth/portalauth.aspx" Destination="/templates/AssetDetail.aspx?id=25769825609" LinkText="(15) Bannières relatives aux applis" />
